import { createHash } from 'node:crypto';
import { copyFile, mkdir, readFile, readdir, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import subsetFont from 'subset-font';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const fontPackage = path.join(root, 'node_modules', '@fontsource', 'noto-serif-sc');
const sourceCss = path.join(fontPackage, '900.css');
const outputDirectory = path.join(root, 'src', 'fonts');
const outputCss = path.join(root, 'src', 'styles', 'generated-font.css');
const generatedPrefix = 'noto-serif-sc-';

async function walk(directory, include) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const absolute = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await walk(absolute, include));
    else if (include(absolute)) files.push(absolute);
  }
  return files;
}

async function corpusFiles() {
  const config = await walk(path.join(root, 'config'), (file) => file.endsWith('.json'));
  const source = await walk(path.join(root, 'src'), (file) =>
    /\.(?:css|ts|tsx)$/.test(file) && file !== outputCss);
  return [...config, ...source, path.join(root, 'index.html')].sort();
}

function unicodeRanges(source) {
  return source.split(',').map((entry) => {
    const match = entry.trim().match(/^U\+([0-9a-f]+)(?:-([0-9a-f]+))?$/i);
    if (!match) throw new Error(`Unsupported unicode range: ${entry}`);
    return [Number.parseInt(match[1], 16), Number.parseInt(match[2] ?? match[1], 16)];
  });
}

function parseFontFaces(source) {
  return [...source.matchAll(/@font-face\s*{[^}]+}/g)].map(([block]) => {
    const file = block.match(/url\(\.\/files\/([^\)]+\.woff2)\)/)?.[1];
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1];
    if (!file || !range) throw new Error('Fontsource 900.css contains an unsupported font-face block');
    return { file, range, intervals: unicodeRanges(range) };
  });
}

function covered(codePoint, face) {
  return face.intervals.some(([start, end]) => codePoint >= start && codePoint <= end);
}

function compactRanges(codePoints) {
  const ordered = [...codePoints].sort((left, right) => left - right);
  const ranges = [];
  let start = ordered[0];
  let end = ordered[0];
  for (const value of ordered.slice(1)) {
    if (value === end + 1) {
      end = value;
      continue;
    }
    ranges.push([start, end]);
    start = value;
    end = value;
  }
  ranges.push([start, end]);
  return ranges.map(([rangeStart, rangeEnd]) =>
    rangeStart === rangeEnd
      ? `U+${rangeStart.toString(16).toUpperCase()}`
      : `U+${rangeStart.toString(16).toUpperCase()}-${rangeEnd.toString(16).toUpperCase()}`).join(',');
}

async function corpus() {
  const files = await corpusFiles();
  const sources = await Promise.all(files.map((file) => readFile(file, 'utf8')));
  const text = sources.join('\n');
  return {
    codePoints: new Set(
      [...text]
        .map((character) => character.codePointAt(0))
        .filter((value) => value >= 0x20 && value !== 0x7f),
    ),
    digest: createHash('sha256').update(text).digest('hex'),
    files,
  };
}

async function selectedFaces() {
  const [fontCss, content] = await Promise.all([readFile(sourceCss, 'utf8'), corpus()]);
  const faces = parseFontFaces(fontCss);
  const selected = faces.flatMap((face) => {
    const codePoints = [...content.codePoints].filter((codePoint) => covered(codePoint, face));
    return codePoints.length > 0 ? [{ ...face, codePoints }] : [];
  });
  const missing = [...content.codePoints].filter((codePoint) =>
    !selected.some((face) => covered(codePoint, face)));
  const missingCjk = missing.filter((value) => value >= 0x2e80 && value <= 0x9fff);
  if (missingCjk.length > 0) {
    throw new Error(`Noto Serif SC cannot cover CJK corpus code points: ${missingCjk.map((value) => `U+${value.toString(16).toUpperCase()}`).join(', ')}`);
  }
  return { content, missing, selected };
}

function generatedCss(faces, missing, digest, fileCount) {
  const blocks = faces.map((face) => `@font-face {
  font-family: "Source Han Serif SC";
  font-style: normal;
  font-display: swap;
  font-weight: 900;
  src: url("../fonts/${face.file}") format("woff2");
  unicode-range: ${compactRanges(face.codePoints)};
}`).join('\n\n');
  const fallback = missing.length > 0
    ? ` System-stack fallback: ${missing.map((value) => `U+${value.toString(16).toUpperCase()}`).join(', ')}.`
    : '';
  return `/* Generated by scripts/subset-font.mjs from ${fileCount} rubric/case/UI files. Corpus sha256:${digest}.${fallback} */\n${blocks}\n`;
}

async function check() {
  const { content, missing, selected } = await selectedFaces();
  const css = await readFile(outputCss, 'utf8');
  if (!css.includes(`Corpus sha256:${content.digest}`)) {
    throw new Error('Generated font CSS is stale; run pnpm font:subset');
  }
  const generatedFiles = new Set([...css.matchAll(/\.\.\/fonts\/([^"\)]+)/g)].map((match) => match[1]));
  for (const face of selected) {
    if (!generatedFiles.has(face.file)) throw new Error(`Generated CSS is missing ${face.file}`);
    await readFile(path.join(outputDirectory, face.file));
  }
  process.stdout.write(`Font subset covers ${content.codePoints.size - missing.length} code points locally and ${missing.length} through the system stack across ${content.files.length} files with ${selected.length} WOFF2 chunks.\n`);
}

async function build() {
  const { content, missing, selected } = await selectedFaces();
  await mkdir(outputDirectory, { recursive: true });
  const existing = await readdir(outputDirectory).catch(() => []);
  await Promise.all(existing
    .filter((file) => file.startsWith(generatedPrefix) && file.endsWith('.woff2'))
    .map((file) => unlink(path.join(outputDirectory, file))));
  await Promise.all(selected.map(async (face) => {
    const source = await readFile(path.join(fontPackage, 'files', face.file));
    const characters = String.fromCodePoint(...face.codePoints);
    const subset = await subsetFont(source, characters, { targetFormat: 'woff2' });
    await writeFile(path.join(outputDirectory, face.file), subset);
  }));
  await copyFile(path.join(fontPackage, 'LICENSE'), path.join(outputDirectory, 'OFL.txt'));
  await writeFile(outputCss, generatedCss(selected, missing, content.digest, content.files.length));
  await check();
}

if (process.argv.includes('--check')) await check();
else await build();
